services:
    app:
        build:
            context: .
            args:
                VARIANT: "3-bullseye"
                BUNDLER_VERSION: "2.6.2"
                RAILS_VERSIONS: "7.2.2.1"
                NODE_VERSION: "22"
        environment:
            BINDING: 0.0.0.0
        volumes:
            - ..:/home/vscode/environment:cached
            - bundle-volume:/usr/local/bundle
        command: sleep infinity
volumes:
    bundle-volume:
